name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # lets you run it manually too

jobs:
  smoke:
    name: Smoke (Chromium)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run smoke tests (@smoke)
        run: npx playwright test --grep @smoke
        # If your config still has multiple projects, force Chromium only:
        # run: npx playwright test --grep @smoke --project=chromium

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-smoke
          path: playwright-report
          if-no-files-found: warn

  regression:
    name: Regression (Chromium)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} # only when manually triggered
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run regression tests (@regression)
        run: npx playwright test --grep @regression
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-regression
          path: playwright-report
          if-no-files-found: warn
